name: Start evaluation jobs

on:
  schedule:
    - cron:  '*/15 * * * *' # Start evaluations every 15th minute

permissions: {}

jobs:

  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python Environment
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Execute scoring script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          AUTOTRAIN_USERNAME: ${{ secrets.AUTOTRAIN_USERNAME }}
          AUTOTRAIN_BACKEND_API: ${{ secrets.AUTOTRAIN_BACKEND_API }}
        run: |
          HF_TOKEN=$HF_TOKEN AUTOTRAIN_USERNAME=$AUTOTRAIN_USERNAME AUTOTRAIN_BACKEND_API=$AUTOTRAIN_BACKEND_API python run_evaluation_jobs.py